version: "3.8"
services:
  web:
    container_name: dandelarosa-blog
    image: jekyll/jekyll:latest
    command: jekyll serve --livereload
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
